export const types = {
  DEFAULT: 'DEFAULT',
  SET_SEARCH: 'SET_SEARCH',
  GET_SEARCH: 'GET_SEARCH',
  SET_FILTERS: 'SET_FILTERS',
  GET_FILTERS: 'GET_FILTERS',
  SET_SETTINGS: 'SET_SETTINGS',
  GET_SETTINGS: 'GET_SETTINGS',
  SET_TOASTIFY: 'SET_TOASTIFY',
  GET_TOASTIFY: 'GET_TOASTIFY',
  SET_AUTH: 'SET_AUTH',
  GET_AUTH: 'GET_AUTH',
}
